FROM mhart/alpine-node:latest AS BUILD_IMAGE

RUN apk add --no-cache libc6-compat && rm -rf /var/cache/apk/*
RUN mkdir /app
WORKDIR /app
COPY package.json yarn.lock ./

RUN yarn --frozen-lockfile

COPY . .
RUN yarn build

FROM nginx:stable-alpine
WORKDIR /app
COPY --from=BUILD_IMAGE /app/dist /etc/nginx/html

