version: "3.8"

services:
  backend:
    container_name: imse-server
    build: ./server/
    volumes:
      - ./server/:/server 
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      MARIADB_USER: imse
      MARIADB_PASSWORD: imse
      MONGODB_USER: root
      MONGODB_PASSWORD: password
    ports:
      - 127.0.0.1:10100:8080
    restart: always
    networks:
      - backend
    depends_on: 
      - mariadb
      - mongo
  mariadb:
    container_name: imse-mariadb
    image: mariadb:10.5
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: imse
      MARIADB_PASSWORD: imse
    restart: always
    networks:
      - backend
  mongo:
    container_name: imse-mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - backend
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

networks:
  backend:
    name: backend_network
  frontend:
    name: frontend_network
