version: "3.8"

services:
  backend-production:
    container_name: imse-server-production
    build:
      context: ./server/
      dockerfile: Dockerfile.production
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      MARIADB_USER: imse
      MARIADB_PASSWORD: imse
      MONGODB_USER: root
      MONGODB_PASSWORD: password
    expose:
      - 8080
    restart: always
    networks:
      - backend
      - frontend
    depends_on:
      - mariadb
      - mongodb
  certbot:
    container_name: imse-certbot-production
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  frontend-production:
    container_name: imse-frontend-production
    build:
      context: ./client/
      dockerfile: Dockerfile.production
    environment:
      - NGINX_HOST=annorum.me
      - NGINX_PORT=80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    networks:
      - frontend
    depends_on:
      - backend-production
  mariadb:
    container_name: imse-mariadb
    image: mariadb:10.5
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: imse
      MARIADB_PASSWORD: imse
    restart: always
    networks:
      - backend
  mongodb:
    container_name: imse-mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend

networks:
  backend:
    name: backend_network
  frontend:
    name: frontend_network