SET foreign_key_checks = 0;
drop table Account;
drop table Student;
drop table Admin;
drop table Event;
drop table Page;
drop table Post;
drop table is_friends_with;
drop table participate;
drop table likes;
SET foreign_key_checks = 1;
